### PR TITLE
Fix for https://github.com/wso2/streaming-integrator/issues/165

### LINKED ISSUE #121: file:move operation does not return false when the source file is not found
**Description:**
file:move operation does not return false when the source file is not found

**Affected Product Version:**
SI 1.1.0

**Steps to reproduce:**
Provide a non existing file as the first arguement. It returns true.

**Related Issues:**
This issue was noticed after the following was fixed:
https://github.com/wso2/streaming-integrator/issues/165

### LINKED ISSUE #124: 'include.by.regexp' and 'exclude.root.dir' parameters in file:move() are not dynamic
**Description:**
- 'include.by.regexp' and 'exclude.root.dir' parameters in file:move() are not dynamic
- When 'exclude.root.dir' parameter is set to true, the destination path does not get created correctly
- When four parameters are given, the regex is always set to ''

**Affected Product Version:**
SI 1.1.0

**OS, DB, other environment details and versions:**  
N/A 

**Steps to reproduce:**
As given in the description.

### LINKED ISSUE #168: Same file gets read periodically when state persistence is enabled
**Description:**
Originally reported by @ramindu90 

Reproducing steps:

@source(type='file', mode='line',
dir.uri='directory/path',
action.after.process='keep',
tailing='false',
@map(type='csv'))
define stream SweetProductionStream (name string, amount long, value long);

Enable state persistence

You may see, the same file getting read at each interval of persisting.

**Affected Product Version:**
SI 1.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Given above.

### LINKED ISSUE #183: File:move() operation with exclude.dir=true does not work as expected in Windows
**Description:**
File:move() operation with exclude.dir=true does not work as expected in Windows

**Affected Product Version:**
SI 1.1.0

**OS, DB, other environment details and versions:**    
Windows 10 Pro

**Steps to reproduce:**
1. Create a file foo.txt in C:\Users\wso2\Desktop\input
2. Deploy below Siddhi app (FileMove) and wait until the app is deployed.
3. List the contents in C:\Users\wso2\Desktop\output folder

Expected output:
foo.txt file only (as it is. It should not be contained in another folder)

Actual output:
Following folder structure can be seen
\Users\wso2\Desktop\input\foo.txt

```
@App:name('FileMove')

@App:description('Moving file from source to target')


define trigger  hardcopyStream at 'start';


@info(name = 'fileMoveQuery')
from hardcopyStream#file:move("C:\Users\wso2\Desktop\input", "C:\Users\wso2\Desktop\output", '', true)
select * 
insert into resultStream;

```

### PR DESCRIPTION
**Pull request by dilini-muthumala**
## Purpose
Improves the fix done for https://github.com/wso2/streaming-integrator/issues/165 by returning false when FileSystemException occurs.
Also 
- resolves https://github.com/wso2/streaming-integrator/issues/168
- resolves https://github.com/siddhi-io/siddhi-io-file/issues/121
- resolves https://github.com/siddhi-io/siddhi-io-file/issues/124
- resolves https://github.com/wso2/streaming-integrator/issues/183

### CODE REVIEW

File: component/src/main/java/io/siddhi/extension/io/file/FileSource.java [hunk 1]
```diff
@@ -618,11 +617,23 @@ public void pause() {
...
-        try {
-            updateSourceConf();
-            deployServers();
-        } catch (ConnectionUnavailableException e) {
-            throw new SiddhiAppRuntimeException("Failed to resume siddhi app runtime.", e);
+        if (dirUri != null && scheduledFuture != null) {
+            this.scheduledFuture = siddhiAppContext.getScheduledExecutorService().
+                    scheduleAtFixedRate(fileSourcePoller, 0, 1, TimeUnit.SECONDS);
+        }
+        if (isTailingEnabled && fileSourceConfiguration.getFileServerConnector() != null) {
```
Comment (ramindu90) [inline component/src/main/java/io/siddhi/extension/io/file/FileSource.java:624]: If tailing disabled, and if its a large file which will take time more than the persisting interval, the file processing may stop. Isnt it?
Shall we use [filePointer](https://github.com/siddhi-io/siddhi-io-file/blob/4858827171969d749751e3f580fa6dee853c83a8/component/src/main/java/io/siddhi/extension/io/file/FileSource.java#L951) and resolve that issue?
This may affect for the files that will be processing in a given dir.uri as well

**Review by ramindu90 — CHANGES_REQUESTED** [review]

File: component/src/main/java/io/siddhi/extension/io/file/FileSource.java (hunk 1 above)
Comment (dilini-muthumala) [reply component/src/main/java/io/siddhi/extension/io/file/FileSource.java:624]: Hi Ramindu, 
In the existing pause() method, the file processing thread is not stopped which is the reason why I thought that there is nothing to resume in the resume() method, assuming that the file will be processed anyway. But let's check this further, to make sure that happens. I have created a separate issue to track this particular issue: https://github.com/siddhi-io/siddhi-io-file/issues/120.

Thanks

**Review by sajithshn — APPROVED** [review]

**Review by ramindu90 — APPROVED** [review]
